import "../styles/globals.css";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { UserAuthContextProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NEXT JS",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div>
          <UserAuthContextProvider>
            <Header />

            {children}
            {/* <Footer/> */}
          </UserAuthContextProvider>
        </div>
      </body>
    </html>
  );
}
